### ISSUE TITLE
Settings Button Covers Disconnect Button

### ISSUE THREAD

**Issue by jmdev91** [cabbagegod/cabbagescape#14] opened 2022-05-15 01:44 UTC
When I have this mod enabled, its settings button sits on top of my Disconnect button in the pause menu. This prevents me from disconnecting at all without closing my client window entirely. I highly recommend switching to a Mod Menu interface for your settings.

**Comment by cabbagegod** [comment] 2022-05-15 11:46
Thanks for the report. Could you provide any more information, like what GUI scale you're using and maybe your monitor resolution? In the meantime, you could see if playing on a different GUI scale would fix this.

**Comment by cabbagegod** [comment] 2022-05-15 11:47
I'm on vacation for like a week but I will work on a patch as soon as I'm home. 👌

**Comment by jmdev91** [comment] 2022-05-17 23:33
I play on gui scale 2/Normal, but testing it at Auto, 1/Small, and 3/Large yielded the same results. As did changing the size of the window arbitrarily. I've narrowed it down to the Mod Menu mod, which is essential for accessing the settings of various other Fabric mods. It adds an extra button over the Disconnect button, shifting it down.

**Comment by cabbagegod** [comment] 2022-05-17 23:38
I see. So it seems cabbagescape is merging poorly with another mod. Unfortunately this is an issue with no perfect fix, some mods just aren't going to be compatible with one another. But I will look at moving the settings button somewhere different for your convenience 😉

**Comment by jmdev91** [comment] 2022-05-18 00:12
Thank you. It's really a good framework for doing mod settings, because of conflicts like this. There's only so much screen space to tack on extra buttons and messing about in config files is too much for a lot of users (plus it requires a whole restart, which can take a while in other situations). Never really understood why Fabric doesn't have this feature built-in like Forge does.

**Comment by cabbagegod** [comment] 2022-06-22 13:02
Will be added to the to-do list for future features but, because it is not a bug with the mod and instead a compatibility issue, I will be closing this topic. Your idea will most likely be finished in version a1.4 so you'll just have to wait for that.

**Closed as completed by cabbagegod** 2022-06-22 13:02 UTC
Labels: bug
